### ISSUE TITLE
Serialization performance

### ISSUE THREAD

**Issue by dxops** [facile-it/paraunit-testcase#12]
The often case for Symfony application in a test environment is Doctrine's caches https://github.com/doctrine/cache/tree/master/lib/Doctrine/Common/Cache. Most of them are using serialization - quite slow and memory sensitive operation.

Suggest to configure or add documentation related to this case. 

The best option is to use `memcached` (`igbinary` behind `memcached`) in the test environment and avoid PHP serialization. Supports all PHP versions and available on Travis (except `igbinary`)

Extensions (commented are optional):
```
extension=memcached.so
;extension=msgpack.so
;extension=igbinary.so
```

config_test.yml will look like
```
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    csrf_protection: true
    profiler:
        enabled: false
    annotations:
        cache: cache.annotations

services:
    memcached:
        class: Memcached
        calls:
            - ['addServer', ['localhost', '11211']]
    cache.test:
        abstract: true
        parent: doctrine_cache.abstract.memcached
        calls:
            - ['setMemcached', ['@memcached']]
    cache.annotations:
        public: false
        parent: cache.test
        calls:
            - [ setNamespace, [ 'annotations_cache' ] ]
    cache.metadata:
        public: false
        parent: cache.test
        calls:
            - [ setNamespace, [ 'metadata_cache' ] ]
    cache.jms_serializer:
        public: false
        parent: cache.test
        calls:
            - [ setNamespace, [ 'jms_serializer_cache' ] ]
    cache.jms_serializer_adapter:
        public: false
        class: Metadata\Cache\DoctrineCacheAdapter
        arguments:
            - 'jms_serializer_cache'
            - '@cache.jms_serializer'

doctrine:
    dbal:
        logging: false
        profiling: false
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id:   cache.metadata

jms_serializer:
    metadata:
        cache: cache.jms_serializer_adapter
```

Another option is to use `ext-redis` + Redis with igbinary support, but it's quite complex to support and configure
https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php#L182-L184
